//商铺
export const BUSINESS_TYPE = 'BUSINESS_TYPE'

//分析
export const REFRESH_DATA_TYPE = 'REFRESH_DATA_TYPE'
export const COMPANY_DATA_NAME = 'COMPANY_DATA_NAME'


//地图
 export const MAP_LOCATION = 'MAP_LOCATION'
 export const MAP_REGION_LOCATION = 'MAP_REGION_LOCATION'
 export const MAP_ROAT_LOCATION = 'MAP_ROAT_LOCATION'
 export const JOB_TYPE = 'JOB_TYPE'
 export const DEL_JOB_TYPR = 'DEL_JOB_TYPR'
 export const REGION_LOCATION_STATE = 'REGION_LOCATION_STATE'
 export const ROAT_LOCATION_STATE = 'ROAT_LOCATION_STATE'
 export const LOCATION_ID = 'LOCATION_ID'
 export const SEARCH_INFO = 'SEARCH_INFO'
 export const SHOW_SEARCH = 'SHOW_SEARCH'

 export const SHOW_TREE = 'SHOW_TREE'
 export const TREE_SHOW = 'TREE_SHOW'

 export const CONTROLER_LIGHT = 'CONTROLER_LIGHT'
 export const CONTROLER_ENVIRONMENT = 'CONTROLER_ENVIRONMENT'
 export const CONTROLER_WIFI = 'CONTROLER_WIFI'
 export const CONTROLER_BROAD = 'CONTROLER_BROAD'
 export const CONTROLER_CAMERA = 'CONTROLER_CAMERA'
 export const CONTROLER_LED = 'CONTROLER_LED'
 export const CONTROLER_TRANSPORT = 'CONTROLER_TRANSPORT'
 export const CONTROLER_SECURITY_PERSON = 'CONTROLER_SECURITY_PERSON'
 export const CONTROLER_SECURITY_SCHEDULE = 'CONTROLER_SECURITY_SCHEDULE'
 export const TRANSPORT_TYPE = 'TRANSPORT_TYPE'

 export const FACILITY_PARK = 'FACILITY_PARK'
 export const FACILITY_TOILET = 'FACILITY_TOILET'
 export const FACILITY_SHOP = 'FACILITY_SHOP'
 export const FACILITY_BUILD = 'FACILITY_BUILD'
 export const FACILITY_SCENIC = 'FACILITY_SCENIC'
 export const FACILITY_TRASH = 'FACILITY_TRASH'
 export const FACILITY_PLANT = 'FACILITY_PLANT'
 export const FACILITY_INDICATOR = 'FACILITY_INDICATOR'
 export const FACILITY_ROAD = 'FACILITY_ROAD'
 export const FACILITY_STATION = 'FACILITY_STATION'
 export const SET_MUSIC='SET_MUSIC'
/*卡片列表显示*/
 export const SHOWBASICICON = 'SHOWBASICICON'
 export const SHOWHARDWAREICON = 'SHOWHARDWAREICON'

// 用户
  export const SET_USER = 'SET_USER'
  export const SET_USER_ROLES = 'SET_USER_ROLES'
  export const SET_USER_DETAIL_INFO = 'SET_USER_DETAIL_INFO'

//  数据基础信息列表
 export const SET_FACILITY_TYPE = 'SET_FACILITY_TYPE'
 export const SET_DEVICE_TYPE = 'SET_DEVICE_TYPE'

//iot
export const CURPAGE = 'CURPAGE'  //测试

// file
export const SET_FILE_TYPE = 'SET_FILE_TYPE'
export const SET_CREATED_STATUS = 'SET_CREATED_STATUS'
export const SET_CRUMBS = 'SET_CRUMBS'
export const SET_CLICK_CRUMBS = 'SET_CLICK_CRUMBS'
export const SELECT_FILE_LIST = 'SELECT_FILE_LIST'
export const DELET_FILE_LIST = 'DELET_FILE_LIST'
export const CRUMBS_LIST = 'CRUMBS_LIST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const MOVE_FILE_SUCCESS = 'MOVE_FILE_SUCCESS'
export const SET_FIX_FILE = 'SET_FIX_FILE'
export const SET_FILE_LIST_LENGTH = 'SET_FILE_LIST_LENGTH'
export const GET_FILE_PAGE_NUMBER = 'GET_FILE_PAGE_NUMBER'
export const SEARCH_FILE_LIST = 'SEARCH_FILE_LIST'
export const CHECK_FILE_ROW = 'CHECK_FILE_ROW'
export const SELECT_ALL = 'SELECT_ALL'
export const FILE_LIST = 'FILE_LIST'

// data
export const DATA_LENGTH = 'DATA_LENGTH'
