//商铺
export const BUSINESS_TYPE = 'BUSINESS_TYPE'

//分析
export const REFRESH_DATA_TYPE = 'REFRESH_DATA_TYPE'

//地图
 export const MAP_LOCATION = 'MAP_LOCATION'
 export const MAP_REGION_LOCATION = 'MAP_REGION_LOCATION'
 export const MAP_ROAT_LOCATION = 'MAP_ROAT_LOCATION'
 export const JOB_TYPE = 'JOB_TYPE'
 export const DEL_JOB_TYPR = 'DEL_JOB_TYPR'
 export const REGION_LOCATION_STATE = 'REGION_LOCATION_STATE'
 export const ROAT_LOCATION_STATE = 'ROAT_LOCATION_STATE'
 export const LOCATION_ID = 'LOCATION_ID'
 export const SEARCH_INFO = 'SEARCH_INFO'
 export const SHOW_SEARCH = 'SHOW_SEARCH'

 export const SHOW_TREE = 'SHOW_TREE'


